import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";

import "jsvectormap/dist/jsvectormap.css";
import "flatpickr/dist/flatpickr.min.css";
import "@/css/satoshi.css";
import "@/css/style.css";
import React, { useEffect, useState } from "react";
import DefaultLayout from "@/components/Layouts/DefaultLayout";
import Products from "@/app/dashboard/products/page";
import Login from "@/app/login/page";
import Dashboard from "@/app/dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(); 

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
          <SessionProvider session={session}>
            <Providers>
              {/* {!session ? <Login /> : <DefaultLayout>{children}</DefaultLayout>} */}
              <DefaultLayout>{children}</DefaultLayout>
            </Providers>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}